"""Add job status and screening notes

Revision ID: 10c7626cca95
Revises: d4d0c4d492cf
Create Date: 2026-09-10 14:47:02.577116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10c7626cca95'
down_revision: Union[str, Sequence[str], None] = 'd4d0c4d492cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('screening_results', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('screening_results', 'notes')
    op.drop_column('jobs', 'status')
    # ### end Alembic commands ###
