"""Add missing fields for P0 stabilization

Revision ID: 4dff423b5cbf
Revises: 2a3972a91237
Create Date: 2026-09-01 14:15:09.215951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dff423b5cbf'
down_revision: Union[str, Sequence[str], None] = '2a3972a91237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('candidate_profiles', sa.Column('total_experience_years', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('department', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('location', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('employment_type', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('requirements', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'requirements')
    op.drop_column('jobs', 'employment_type')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'department')
    op.drop_column('candidate_profiles', 'total_experience_years')
    op.drop_column('candidate_profiles', 'summary')
    # ### end Alembic commands ###
