"""add_interview_provider_fields

Revision ID: 658ae7b0f980
Revises: c3c8ec9c7554
Create Date: 2026-09-12 12:08:39.675417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658ae7b0f980'
down_revision: Union[str, Sequence[str], None] = 'c3c8ec9c7554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('provider', sa.String(length=50), nullable=True))
    op.add_column('interviews', sa.Column('provider_run_id', sa.String(length=100), nullable=True))
    op.add_column('interviews', sa.Column('public_token', sa.String(length=64), nullable=True))
    op.add_column('interviews', sa.Column('link_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interviews', sa.Column('transcript_url', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('recording_url', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interviews', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_interviews_public_token'), 'interviews', ['public_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviews_public_token'), table_name='interviews')
    op.drop_column('interviews', 'completed_at')
    op.drop_column('interviews', 'scheduled_at')
    op.drop_column('interviews', 'recording_url')
    op.drop_column('interviews', 'transcript_url')
    op.drop_column('interviews', 'link_expires_at')
    op.drop_column('interviews', 'public_token')
    op.drop_column('interviews', 'provider_run_id')
    op.drop_column('interviews', 'provider')
    # ### end Alembic commands ###
