"""Add embedding_profile and embedding_status to Job

Revision ID: 70d37338f17f
Revises: 7371be426279
Create Date: 2026-09-06 14:05:47.503449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '70d37338f17f'
down_revision: Union[str, Sequence[str], None] = '7371be426279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('embedding_profile', sa.String(length=255), nullable=True))
    op.add_column('jobs', sa.Column('embedding_status', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'embedding_status')
    op.drop_column('jobs', 'embedding_profile')
    # ### end Alembic commands ###
