"""make screening fields nullable for pre-screening

Revision ID: b9092c02e5fc
Revises: 70d37338f17f
Create Date: 2026-09-09 16:47:13.643146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b9092c02e5fc'
down_revision: Union[str, Sequence[str], None] = '70d37338f17f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_interview_job_resume', 'interviews', ['job_id', 'resume_id'])
    op.drop_column('jobs', 'requirements')
    op.drop_column('jobs', 'location')
    op.drop_column('jobs', 'employment_type')
    op.drop_column('jobs', 'department')
    op.alter_column('screening_results', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('screening_results', 'strengths',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('screening_results', 'gaps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('screening_results', 'evidence',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('screening_results', 'evidence',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('screening_results', 'gaps',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('screening_results', 'strengths',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('screening_results', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.add_column('jobs', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('employment_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('requirements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint('uq_interview_job_resume', 'interviews', type_='unique')
    # ### end Alembic commands ###
