"""add interview outcome states retry generation fence

Revision ID: 8c93135170fd
Revises: 0dec6f84f85b
Create Date: 2026-09-24 12:38:07.201179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c93135170fd'
down_revision: Union[str, Sequence[str], None] = '0dec6f84f85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('outcome', sa.String(length=50), nullable=True))
    op.add_column('interviews', sa.Column('provider_run_attempt', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###

    # Manually added: backfill provider_run_attempt for existing rows that
    # already have a provider_run_id. Without this, the new
    # attempt-generation guard in receive_evaluation would compare
    # retry_count (0, from the server_default above) against
    # provider_run_attempt (NULL, no default) and treat them as "distinct",
    # wrongly rejecting every existing interview's next legitimate webhook
    # as stale. retry_count is universally 0 for every pre-existing row at
    # migration time - no retry could have happened before this feature
    # existed - so backfilling from that column (rather than hardcoding 0)
    # keeps the intent self-documenting and correct if ever re-run.
    op.execute("UPDATE interviews SET provider_run_attempt = retry_count WHERE provider_run_id IS NOT NULL")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'retry_count')
    op.drop_column('interviews', 'provider_run_attempt')
    op.drop_column('interviews', 'outcome')
    # ### end Alembic commands ###
