"""add_talent_pool_entries

Revision ID: c3c8ec9c7554
Revises: 238ccec3369a
Create Date: 2026-09-12 11:36:38.291727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3c8ec9c7554'
down_revision: Union[str, Sequence[str], None] = '238ccec3369a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('talent_pool_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('added_from_job_id', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['added_from_job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_talent_pool_entries_added_from_job_id'), 'talent_pool_entries', ['added_from_job_id'], unique=False)
    op.create_index(op.f('ix_talent_pool_entries_id'), 'talent_pool_entries', ['id'], unique=False)
    op.create_index(op.f('ix_talent_pool_entries_resume_id'), 'talent_pool_entries', ['resume_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_talent_pool_entries_resume_id'), table_name='talent_pool_entries')
    op.drop_index(op.f('ix_talent_pool_entries_id'), table_name='talent_pool_entries')
    op.drop_index(op.f('ix_talent_pool_entries_added_from_job_id'), table_name='talent_pool_entries')
    op.drop_table('talent_pool_entries')
    # ### end Alembic commands ###
